name: terratales
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  flutter_colorpicker: ^1.0.3
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  table_calendar: ^3.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Rake.jpg
    - assets/images/Shovel.jpg
    - assets/images/HedgeShear.jpg
    - assets/images/Trowel.jpg
    - assets/images/Axe.jpg
    - assets/images/Dibber.jpg
    - assets/images/GardenFork.jpg
    - assets/images/GardenGloves.jpg
    - assets/images/GardenHoe.jpg
    - assets/images/GardeningCan.jpg
    - assets/images/Loppers.jpg
    - assets/images/Mattock.jpg
    - assets/images/Sickle.jpg
    - assets/images/Weeder.jpg
    - assets/images/WheelBarrow.jpg
    - assets/images/profile.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf

    - family: BrightRetro
      fonts:
        - asset: assets/fonts/bright.otf